pkg/kvm-tools: delete
It seems kvmtool is not used in EVE (anymore)

There is no way to activate it and there is no documentation on how
to use it.
Trying to trigger the rootfs yaml modifier script ends up in an error:
```
tools/compose-image-yml.sh -b images/rootfs.yml.in -v "0.0.0-rm_kvmtool-825d7805-kvm-generic-amd64" -o images/out/rootfs-kvm-generic.yml.in -h kvm -p generic images/modifiers/platform/tools/tools.yq ; wc -l images/out/rootfs-kvm-generic.yml.in
Error: cannot index array with '+' (strconv.ParseInt: parsing "+": invalid syntax)
3 images/out/rootfs-kvm-generic.yml.in
```

Signed-off-by: Christoph Ostarek <christoph@zededa.com>
(cherry picked from commit 63db07666b8e57ba8e29e4c4e82eac7ee0beb06e)