wwan: Explicitly request IPv4 connection
Without explicitly asking for IPv4 (which we only support for wwan),
for some LTE networks the connect request may fail with:

error: couldn't start network: QMI protocol error (14): 'CallFailed'
call end reason (1): generic-unspecified
verbose call end reason (6,50): [3gpp] ipv4-only-allowed

This error is returned by network to indicate that only PDN type IPv4
is allowed for the requested PDN connectivity (which is want we want
but we need to be explicit about it).

Signed-off-by: Milan Lenco <milan@zededa.com>