pillar/Makefile: fix $(shell ) build-docker-test
$(shell ...) is evaluated immediately and not on the line
it is executed on, therefore build-docker-test needs to be
split into three different targets

otherwise an error message like this shows up:
```
Dockerfile:19
--------------------
  17 |
  18 |     FROM ${REL_HASH_LFEDGE_EVE_UEFI} AS uefi-build
  19 | >>> FROM ${REL_HASH_LFEDGE_EVE_DOM0_ZTOOLS} AS zfs
  20 |     RUN mkdir /out
  21 |     # copy zfs-related files from dom0-ztools using prepared list of files
--------------------
ERROR: failed to build: failed to solve: lfedge/eve-dom0-ztools:000adaabe42b4f34dc196b722f143d3ae39f47fa-dirty-cb3d84e: failed to resolve source metadata for docker.io/lfedge/eve-dom0-ztools:000adaabe42b4f34dc196b722f143d3ae39f47fa-dirty-cb3d84e: docker.io/lfedge/eve-dom0-ztools:000adaabe42b4f34dc196b722f143d3ae39f47fa-dirty-cb3d84e: not found
```

Signed-off-by: Christoph Ostarek <christoph@zededa.com>