pkg/fscrypt: bump up version v0.2.4 -> v0.3.4
This patch bumps up fscrypt version from v0.2.4 to v0.3.4.
There are two things done here:

1. Change fscrypt SHA in Dockerfile to the v0.3.4 tag
2. Adopt our local patches for the newest version of the fscrypt

From software engineering perspective this commit is rather boring
(update package from older version to newer, we do this often, who
cares) but motivation of this change goes far deeper. Here is the
story.

Noticeable fscrypt evolution happened in version v0.2.6, where v2
policies began to be supported. A few lines from the fscrypt release
notes related to the 0.2.6 version:

 The big feature in this release is support for v2 kernel encryption
 policies. With the release of Linux 5.4, the kernel added a
 [new type of policy](https://www.kernel.org/doc/html/latest/filesystems/fscrypt.html)
 that makes `fscrypt` much easier to use.  For directories using
 these new policies:

    [ cut ]

    * The policies are no longer tied to the buggy kernel keyring API.
        * This removes the need for users to run `keyctl link` or to
	  reconfigure `pam_keyinit`.

What does it fix?

On ext4 EVE unlocks /persist/vault folder (where all customer volumes
and images are safely kept) utilizing old 0.2.4 version of
fscrypt, so kernel keyring API was used (so called v1 policies).

Since /persist/vault folder was unlocked by the pillar proces from the
pillar service container, kernel keyring was bound to that process and
that mount namespace, not across the system. Very interesting side
effect of this behaviour is that if a file exists in the inode cache,
then file can be read by any process from any namespace, but if caches
are empty, then process receives ENOKEY (132) "Required key not available"
errno.

Short illustration of the problem:

 # eve enter debug
 # cat /persist/vault/volumes/177eafd2-0bdd-498a-9369-20531f6cd344\#0.container/ug > /dev/null
 # echo 2 > /proc/sys/vm/drop_caches
 # cat /persist/vault/volumes/177eafd2-0bdd-498a-9369-20531f6cd344\#0.container/ug > /dev/null
 cat: can't open '/persist/vault/volumes/177eafd2-0bdd-498a-9369-20531f6cd344#0.container/ug': Required key not available

The whole sequence was executed right after a container application
was started, so inode cache was populated. After cache eviction any
file from the vault can't be accessed any more by the debug container.

The problem spreads even further: after cache eviction files can't be
accessed from the shim VM as well:

 # touch /mnt/test
 touch: /mnt/test: Required key not available

 # cat /mnt/ug
 cat: can't open '/mnt/ug': Required key not available

Entering container from the shim VM also stops working, because
required /mnt/entrypoint-pid file can't be created:

 # eve-enter-container
 Error: PID file '/mnt/entrypoint-pid' not found. Container did not start?

This leads to shim VM crashes if inode cache on host was evicted and
shim VM was rebooted.

Also same issue is observed on docker (worth reading!):
https://github.com/google/fscrypt/issues/128

Switching to the new fs keyring (v2 policies, starting from v0.2.6
of the fscrypt) eliminates described problem and unlocks vault
across the system.

This patch only updates pkg/fscrypt container, but new fscrypt version
is not yet part of the resulting rootfs image, this commit follows.

Signed-off-by: Roman Penyaev <r.peniaev@gmail.com>
(cherry picked from commit 66af83323269e3a10b3cd0f9602617fea1064d84)